name: continuous-integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-js:
    runs-on: ubuntu-latest
    name: Lint Javascript

    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - run: yarn install
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    name: "Ensure build completes"
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - run: yarn install
      - env:
          NODE_ENV: development
        run: yarn build:ci
